/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.4.32")
    implementation("io.cucumber:cucumber-guice:6.10.2")
    implementation("io.cucumber:cucumber-java8:6.10.2")
    implementation("io.cucumber:cucumber-core:6.10.2")
    implementation("io.cucumber:cucumber-junit:6.10.2")
    implementation("org.slf4j:slf4j-api:1.7.30")
    implementation("com.google.inject:guice:4.2.2")
    runtimeOnly("ch.qos.logback:logback-classic:1.2.3")
    testImplementation("junit:junit:4.13.1")
}

group = "com.jecklgamis"
version = "1.0.0-SNAPSHOT"
description = "cucumber-jvm-kotlin-example"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
